version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config:/etc/prometheus/
    networks:
      - monitoring_network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
    pid: host
    restart: unless-stopped
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_SERVER_HTTP_PORT=3030
    ports:
      - '3030:3030'
    volumes:
      - 'grafana_storage:/var/lib/grafana'

    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge

volumes:
  grafana_storage: {}
